export const constantVariables = {
  online: 'Online',
  oneToOne: 'In Person',
  learnerLevelOptions: [
    { name: 'Any' },
    { name: 'Elementary' },
    { name: 'Middle School' },
    { name: 'High School' },
    { name: 'College' },
    { name: 'Adult' },
  ],
  suitableoptions: [
    'Any',
    'Elementary',
    'Middle School',
    'High School',
    'College',
    'Adult',
  ],
  coursetype: ['1-1', 'Group'],
  coursemode: ['Online', 'In Person'],
  swalErrorOption: {
    container: 'error_container_class',
    popup: 'error_popup_class',
    header: 'error_header_class',
    title: 'error_title_class',
    closeButton: 'error_close_button_class',
    icon: 'error_icon_class  d-none',
    image: 'error_image_class',
    content: 'error_content_class',
    input: 'error_input_class',
    actions: 'error_actions_class',
    confirmButton: 'error_confirm_button_class',
    cancelButton: 'error_cancel_button_class',
    footer: 'error_footer_class',
  },
  swalSuccessOption: {
    container: 'success_container_class',
    popup: 'success_popup_class',
    header: 'success_header_class',
    title: 'success_title_class',
    closeButton: 'success_close_button_class',
    icon: 'success_icon_class  d-none',
    image: 'success_image_class',
    content: 'success_content_class',
    input: 'success_input_class',
    actions: 'success_actions_class',
    confirmButton: 'success_confirm_button_class',
    cancelButton: 'success_cancel_button_class',
    footer: 'success_footer_class',
  },

  swalInfoOption: {
    container: 'info_container_class',
    popup: 'info_popup_class',
    header: 'info_header_class',
    title: 'info_title_class',
    closeButton: 'info_close_button_class',
    icon: 'info_icon_class  d-none',
    image: 'info_image_class',
    content: 'info_content_class',
    input: 'info_input_class',
    actions: 'info_actions_class',
    confirmButton: 'info_confirm_button_class',
    cancelButton: 'info_cancel_button_class',
    footer: 'info_footer_class',
  },
  swalWarningOption: {
    container: 'warning_container_class',
    popup: 'warning_popup_class',
    header: 'warning_header_class',
    title: 'warning_title_class',
    closeButton: 'warning_close_button_class',
    icon: 'warning_icon_class  d-none',
    image: 'warning_image_class',
    content: 'warning_content_class',
    input: 'warning_input_class',
    actions: 'warning_actions_class',
    confirmButton: 'warning_confirm_button_class',
    cancelButton: 'warning_cancel_button_class',
    footer: 'warning_footer_class',
  },
  statusArray: {
    Complete: {
      type: 'Complete',
      class: 'green',
      icon: 'fal fa-check-circle',
    },
    Cancelled: { type: 'Cancelled', class: 'green', icon: 'fal fa-ban' },
    Refunded: { type: 'Refunded', class: 'yellow', icon: 'fal fa-undo' },
    Pending: {
      type: 'Pending',
      class: 'yellow',
      icon: 'fal fa-hourglass-half',
    },
    Rejected: {
      type: 'Rejected',
      class: 'red',
      icon: 'fal fa-times-circle',
    },
    Deleted: { type: 'Deleted', class: 'red', icon: 'fal fa-trash' },
    Dispute: {
      type: 'Dispute',
      class: 'yellow',
      icon: 'fal fa-thumbs-down',
    },
    Closed: { type: 'Closed', class: 'green', icon: 'fal fa-times' },
    Requested: {
      type: 'Requested',
      class: 'green',
      icon: 'fal fa-question-circle',
    },
    Confirmed: {
      type: 'Confirmed',
      class: 'green',
      icon: 'fal fa-check-circle',
    },
    'In Progress': {
      type: 'In Progress',
      class: 'green',
      icon: 'fal fa-spinner',
    },
    'In Dispute': {
      type: 'In Dispute',
      class: 'red',
      icon: 'fal fa-spinner',
    },
    Completed: {
      type: 'Completed',
      class: 'green',
      icon: 'fal fa-check-circle',
    },
    Expired: {
      type: 'Expired',
      class: 'red',
      icon: 'fal fa-exclamation-triangle',
    },
    Created: {
      type: 'Created',
      class: 'yellow',
      icon: 'fal fa-check-circle',
    },
  },

  startHoursArr: [
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    '11',
    '12',
  ],
  startMinutesArr: [
    '00',
    '01',
    '02',
    '03',
    '04',
    '05',
    '06',
    '07',
    '08',
    '09',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48',
    '49',
    '50',
    '51',
    '52',
    '53',
    '54',
    '55',
    '56',
    '57',
    '58',
    '59',
  ],

  FORM_TYPE: {
    ALL : 'All',
    DOCUMENT: 'document_upload',
    BASIC: 'basic_information'
  }
};
